d /run/myuna-telegram-gateway 0750 root myuna-gateway-telegram -
d /var/lib/myuna-telegram-gateway 0750 myuna-gateway-telegram myuna-gateway-telegram -
d /var/log/myuna-telegram-gateway 0750 myuna-gateway-telegram myuna-gateway-telegram -
