"""Inactive P09/V7 structured-affinity contract and synthetic reducer."""

from .contracts import (
    ABSTENTION_REASONS,
    AFFINITY_DIMENSIONS,
    AUDIT_NAMESPACE,
    CAPABILITY_ID,
    CONFIDENCE_BANDS,
    FIXTURE_SCHEMA,
    LONG_TERM_DIMENSIONS,
    SCHEMA_LABEL,
    SCHEMA_VERSION,
    SHORT_TERM_DIMENSIONS,
    AffinityCapabilityContract,
    AffinityDependencyContract,
    AffinityDimensionState,
    AffinityError,
    AffinitySnapshot,
    AffinityTimeSample,
    AffinityUpdate,
)
from .ports import (
    AffinityDiagnosticEvent,
    AffinityEvidenceQuery,
    AffinityEvidenceReference,
    AffinityRelevanceResult,
    P07ExternalContextAffinityPort,
    P07OwnerProfileAffinityPort,
    P08TemporalAffinityPort,
    P10TrustedTimeAffinityPort,
    P15AffinityRelevancePort,
    P16AffinityDiagnosticsPort,
)
from .state_machine import AffinityTransition, SyntheticAffinityStateMachine

__all__ = [
    "ABSTENTION_REASONS",
    "AFFINITY_DIMENSIONS",
    "AUDIT_NAMESPACE",
    "CAPABILITY_ID",
    "CONFIDENCE_BANDS",
    "FIXTURE_SCHEMA",
    "LONG_TERM_DIMENSIONS",
    "SCHEMA_LABEL",
    "SCHEMA_VERSION",
    "SHORT_TERM_DIMENSIONS",
    "AffinityCapabilityContract",
    "AffinityDependencyContract",
    "AffinityDiagnosticEvent",
    "AffinityDimensionState",
    "AffinityError",
    "AffinityEvidenceQuery",
    "AffinityEvidenceReference",
    "AffinityRelevanceResult",
    "AffinitySnapshot",
    "AffinityTimeSample",
    "AffinityTransition",
    "AffinityUpdate",
    "P07ExternalContextAffinityPort",
    "P07OwnerProfileAffinityPort",
    "P08TemporalAffinityPort",
    "P10TrustedTimeAffinityPort",
    "P15AffinityRelevancePort",
    "P16AffinityDiagnosticsPort",
    "SyntheticAffinityStateMachine",
]
